language: ruby
rvm:
- 2.2

matrix:
  allow_failures:
    - rvm: 2.2

before_install:
 - nvm install node

install:
 - npm install -g csslint
 - bundle install

script:
 - bash .travis/cibuild
 - csslint _site/css/gallery.css
 - csslint _site/css/logo-nav.css
 - csslint _site/css/syntax.css

# branch whitelist, only for GitHub Pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
